apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: camel-k-source-repo
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/masauve/camelk-demo