apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/instance: camelk-dev
  name: camel-k-run-integration
  namespace: camelk-dev
spec:
  params:
    - name: traits
      type: array
    - description: The integration file to run
      name: file
      type: string
  resources:
    inputs:
      - name: repository
        type: git
  steps:
    - args:
        - run
        - '$(params.traits[*])'
        - $(params.file)
      command:
        - kamel
      image: 'apache/camel-k:1.7.0'
      name: run-integration
      resources: {}
      workingDir: /workspace/repository
