apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: creditservice-pipeline-run-
spec:
  pipelineRef:
    name: creditservice-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: camel-k-source-repo
  serviceAccountName: pipeline
  timeout: 1h0m0s
