openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /transaction:
        get:
            responses:
                '200': {}
            operationId: readtransaction
            summary: Read and Write user transaction            
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Transaction'
                required: true
            responses:
                '200':
                    content:
                        application/json: {}
            operationId: writetransaction                  
components:
    schemas:
        Transaction:
            title: Root of Transaction
            description: 'transaction description  '
            type: object
            properties:
                accoutId:
                    type: string
                transactionId:
                    type: string
                transactionCategory:
                    type: string
                posdtedTimestamp:
                    type: string
                transactionDescription:
                    type: string
                debitCreditDemo:
                    type: string
                amount:
                    format: double
                    type: number                    
            example:
                accoutId: 10001
                transactionId: 20001
                transactionCategory: DEPOSIT_ACCOUNT_TRANSACTION
                posdtedTimestamp: 2022-09-05T13:15:30.751Z
                transactionDescription: Direct deposit from XYZ
                debitCreditDemo: DEPOSIT
                amount: 1200