openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /debit:
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Transaction'
                    description: List all transactions
            operationId: getall
        post:
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Transaction'
                        examples:
                            client:
                                value:
                                    clientId: client1
                                    type: debit
                                    location: The car coffeeshop
                                    amount: 4.25
                required: true
            responses:
                '200':
                    description: Deposit received
            description: Insert a debit request in the debit store
            operationId: writedb
components:
    schemas:
        Transaction:
            title: Root of Transaction
            description: 'transaction description  '
            type: object
            properties:
                accoutId:
                    type: string
                transactionId:
                    type: string
                transactionCategory:
                    type: string
                posdtedTimestamp:
                    type: string
                transactionDescription:
                    type: string
                debitCreditDemo:
                    type: string
                amount:
                    format: double
                    type: number                    
            example:
                accoutId: 10001
                transactionId: 20001
                transactionCategory: DEPOSIT_ACCOUNT_TRANSACTION
                posdtedTimestamp: 2022-09-05T13:15:30.751Z
                transactionDescription: Direct deposit from XYZ
                debitCreditDemo: Deposit
                amount: 1200