kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: environments
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: environments
  source:
    path: manifests/gitops/overlays/01-infra/00-setup
    repoURL: https://github.com/masauve/camelk-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true