apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: CamelK Demo - DEV
    openshift.io/display-name: CamelK Demo - DEV
  labels:
    argocd.argoproj.io/managed-by: argocd
  name: camelk-dev
