apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: debit-auth
spec:
  selector:
    matchLabels:
      camel.apache.org/integration: debitservice
  jwtRules:
  - issuer: https://keycloak-dev.apps.home.myocp.net/realms/apps
    jwksUri: https://keycloak-dev.apps.home.myocp.net/realms/apps/protocol/openid-connect/certs
    forwardOriginalToken: true
