kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd-developers
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd-developers
  source:
    path: manifests/gitops/overlays/02-argocd-for-developers
    repoURL: https://github.com/masauve/camelk-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
