openapi: 3.0.2
info:
    title: New API
    version: 1.0.0
    description: A brand new API with no content.  Go nuts!
paths:
    /accounts:
        post:
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Account'
                required: true
            responses:
                '200':
                    content:
                        description: Account created
                        application/json: {}
                        schema:
                            $ref: '#/components/schemas/Account'
            description: Create a new Account
            operationId: createAccount
    /accounts/{accountId}:
        get:
            responses:
                '200': {}
            operationId: getAnAccount
            summary: Get a particular account                    
    /accounts/{accountId}/transactions:
        get:
            responses:
                '200': {}
            operationId: getAccountTransaction
            summary: Get a particular account transactions                   
components:
    schemas:
        Account:
            description: Account information
            type: object
            properties:
                accountId:
                    type: string
                accountType: 
                    type: string
                displayName:
                    type: string
                status:
                    type: string
                description:
                    type: string
                nickname:
                    type: string
                currency:
                    $ref: '#/components/schemas/CurrenryInfo'
                interestRate:
                    format: double
                    type: number
                loanTerm:
                    format: double
                    type: number
                totalNumberOfPayments:
                    format: double
                    type: number
                currentBalance:
                    format: double
                    type: number
                availableBalance:
                    format: double
                    type: number
        CurrenryInfo:
            type: object
            properties:
                currencycode:
                    type: string