apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: camelk
  namespace: camelk-dev
spec:
  targetNamespaces:
    - camelk-dev
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: camel-k
  namespace: camelk-dev
spec:
  channel: stable-1.11
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: camel-k-operator.v1.11.0